// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9BOFXoEsv4DESKSdq1JNvyCFnDevCPB4',
    appId: '1:490673328576:web:d71e649f5f8296be85b825',
    messagingSenderId: '490673328576',
    projectId: 'unicah-app-t',
    authDomain: 'unicah-app-t.firebaseapp.com',
    storageBucket: 'unicah-app-t.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDviiFa7mXaUCthPc-35Hq3mz7oHJHagOU',
    appId: '1:490673328576:android:6626e36ca0d4ff1385b825',
    messagingSenderId: '490673328576',
    projectId: 'unicah-app-t',
    storageBucket: 'unicah-app-t.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVbpLu61CarHhcEWdxgWFvlhcGdygFGI0',
    appId: '1:490673328576:ios:b5c6ff3029cbf52e85b825',
    messagingSenderId: '490673328576',
    projectId: 'unicah-app-t',
    storageBucket: 'unicah-app-t.firebasestorage.app',
    iosBundleId: 'com.example.unicahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVbpLu61CarHhcEWdxgWFvlhcGdygFGI0',
    appId: '1:490673328576:ios:b5c6ff3029cbf52e85b825',
    messagingSenderId: '490673328576',
    projectId: 'unicah-app-t',
    storageBucket: 'unicah-app-t.firebasestorage.app',
    iosBundleId: 'com.example.unicahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9BOFXoEsv4DESKSdq1JNvyCFnDevCPB4',
    appId: '1:490673328576:web:1f3d67d569a909d685b825',
    messagingSenderId: '490673328576',
    projectId: 'unicah-app-t',
    authDomain: 'unicah-app-t.firebaseapp.com',
    storageBucket: 'unicah-app-t.firebasestorage.app',
  );
}
